name: EmotionRecML
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.1
  - ipykernel=6.29.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - matplotlib=3.8.2
  - numpy=1.26.3
  - pandas=2.2.0
  - scikit-learn=1.4.0
  - scipy=1.12.0
  - seaborn=0.13.2
  - pip=23.3.2
  - setuptools=69.0.3
  - wheel=0.42.0
  - pip:
    - imbalanced-learn==0.12.0
    - modal==0.61.45
    - torch==2.2.1
    - torchvision==0.17.1