name: EmotionRecML

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12.1
  - ipykernel=6.29.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - matplotlib-inline=0.1.6
  - pip=23.3.2
  - setuptools=69.0.3
  - wheel=0.42.0
  - pip:
    - contourpy==1.2.0
    - cycler==0.12.1
    - filelock==3.13.1
    - fonttools==4.47.2
    - fsspec==2024.2.0
    - imbalanced-learn==0.12.0
    - imblearn==0.0
    - jinja2==3.1.3
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - markupsafe==2.1.5
    - matplotlib==3.8.2
    - mpmath==1.3.0
    - networkx==3.2.1
    - numpy==1.26.3
    - pandas==2.2.0
    - pillow==10.2.0
    - pyparsing==3.1.1
    - pytz==2024.1
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - sympy==1.12
    - threadpoolctl==3.2.0
    - torch==2.2.1
    - torchvision==0.17.1
    - tzdata==2023.4